server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 37a93236e0e10d7dffd0
            client-secret: 0f4e5ce2f1ab01ef04ebe1217859259d6fee2960

frontend:
  url: http://localhost:3000/success